- name: creating ec2 and r53 
  hosts: local
  connection: local
  #   vars_files:
  # - vars.yaml
  tasks:
  - name: installing python dependencies
    ansible.builtin.pip:
      name: 
      - boto3
      - botocore
      executable: pip3.9

  - name: creating ec2 instances.
    amazon.aws.ec2_instance:
      name: mysql
      vpc_subnet_id: "subnet-0e541222b36806bcc" #variable declared in vars.yaml file
      instance_type: "t2.micro"
      security_group: "sg-077917637fc069d1f" #variable declared in vars.yaml file
      image_id: "ami-09c813fb71547fc4f" #variable declared in vars.yaml file
      region: "us-east-1"
    #register: ec2_instances # output assingd to variable ec2_instances
   
